
name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: test123
          MYSQL_DATABASE: test
          MYSQL_ALLOW_EMPTY_PASSWORD: no
          MYSQL_USER: admin
          MYSQL_PASSWORD: test123

        ports:
          - "3310:3310"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build --if-present
          start: npm run cypress:open
        env:
          CYPRESS_host: ${{secrets.CYPRESS_HOST}}
          CYPRESS_database: ${{ secrets.CYPRESS_DATABASE }}
          CYPRESS_user: ${{secrets.CYPRESS_USER}}
          CYPRESS_password: ${{secrets.CYPRESS_PASSWORD }}
          CYPRESS_port: ${{ secrets.CYPRESS_PORT }}
